version: '3.7'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: streamcave
        ports: ["3306"]
        expose:
            -   "3306"
    mailer:
        container_name: mailer
        image: schickling/mailcatcher
        ports: [ "1025", "1080" ]