api_platform:
    resource: .
    type: api_platform
    prefix: /api
login_manage_logout:
  path: /login_manage/logout
  controller: App\Controller\LogoutController::logout
  methods: [ 'GET' ]
login_manage_refresh:
  path: /login_manage/refresh
  controller: App\Controller\TokenController::index
  methods: [ 'GET' ]
login_manage_revoke_discord:
  path: /login_manage/revoke_discord
  controller: App\Controller\TokenController::revokeDiscordToken
  methods: [ 'POST' ]
login_manage_refresh_discord:
  path: /login_manage/refresh_discord
  controller: App\Controller\TokenController::discordToken
  methods: [ 'POST' ]
login_manage_revoke_twitch:
  path: /login_manage/revoke_twitch
  controller: App\Controller\TokenController::revokeTwitchToken
  methods: [ 'POST' ]
login_manage_refresh_twitch:
  path: /login_manage/refresh_twitch
  controller: App\Controller\TokenController::refreshTwitchToken
  methods: [ 'POST' ]